export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const ERROR = 'ERROR';
export const FETCH_ALL = 'FETCH_ALL';
export const FETCH = 'FETCH'
export const FETCH_EMPTY_ROOMS = 'FETCH_EMPTY_ROOMS'
export const LIKE = 'LIKE';
export const FETCH_REVIEWS_BY_HOSTEL = 'FETCH_REVIEWS_BY_HOSTEL'

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const FETCH_USER = 'FETCH_USER'

export const END_LOADING = 'END_LOADING';
export const START_LOADING = 'START_LOADING';

export const FETCH_HOSTEL = 'FETCH_HOSTEL'

export const FETCH_ROOM_REQUEST_BY_HOSTEL_ID = 'FETCH_ROOM_REQUEST_BY_HOSTEL_ID'
export const FETCH_ROOM_BY_HOSTEL_ID = 'FETCH_ROOM_BY_HOSTEL_ID'
export const FETCH_COMPLAINTS_BY_HOSTEL_ID = 'FETCH_COMPLAINTS_BY_HOSTEL_ID'
export const FETCH_TENANT_BY_USER_ID = 'FETCH_TENANT_BY_USER_ID'
export const FETCH_TENANT_BY_HOSTEL_ID = 'FETCH_TENANT_BY_HOSTEL_ID'

export const FETCH_ROOM_BY_ROOM_ID = 'FETCH_ROOM_BY_ROOM_ID'
export const BOOK = 'BOOK'
export const LEAVE = 'LEAVE'